### ISSUE TITLE
original ticket can be edited if any one is logged in

### ISSUE THREAD

**Issue by ltemimi** [ADefWebserver/SyncfusionHelpDesk#10]
To make the top part of the ticket (original part) disabled checks are on whether the logged-in used is authenticated not if the role is administrators. But any user can register and login.

Is it assumed that only admin user is going to log in? 

Please help

Laz

**Comment by ADefWebserver** [comment]
@ltemimi  - It is *assumed* that only the Administrator is logging in. However, the code is 'simplified' to work with the expected size of the accompanying book. Thanks
