### ISSUE TITLE
URL computation does not work with Azure

### ISSUE THREAD

**Issue by ltemimi** [ADefWebserver/SyncfusionHelpDesk#12]
Hi
After a ticket has been saved an email is sent to admin (or user) with the ticket URL. This works well when using the helpdesk app on my PC BUT does not when deployed to azure; the computed url is :

Help Desk Ticket Created: :///emailticketedit/76cc3440-6690-41e5-877f-b74484792e67

The website address is not present

Regards
Laz

**Comment by ADefWebserver** [comment]
The proper thing to do is to allow the proper base path of your website to be set (either in the database, or the appsettings.json file).

Sorry, that wasn't covered (on purpose to keep the book short).

**Comment by ltemimi** [comment]
Hi 
Thanks good idea I shall do the base path in appsettings.json
