### ISSUE TITLE
TimeOut attribute renamed to Timeout in Syncfusion.Blazor 19.4.0.xx

### ISSUE THREAD

**Issue by HiveTyrant** [ADefWebserver/SyncfusionHelpDesk#13]
When using code from GitHub repository, but upgrading to latest Suncfusion.Blazor (currently 19.4.0.50) nuget package, the program will fail as SfToast.TimeOut property has changed name.

Code needs to be changed in the Index.razor file, line 18

Before: 
          Content="@ToastContent" TimeOut="5000">

After: 
          Content="@ToastContent" Timeout="5000">

**Comment by ADefWebserver** [comment]
Unfortunately, I need to keep the code 'frozen' to match the book. Thanks!
