### ISSUE TITLE
Send Email not working?

### ISSUE THREAD

**Issue by kvenda** [ADefWebserver/SyncfusionHelpDesk#2]
Is it possible sendgrid may not be working with the latest release of Blazor? Using server side Blazor latest RC. No error message is generated, but no email. I have rebuilt entire HelpDesk using files from repo, still no luck. But everything else is working!

**Comment by ADefWebserver** [comment]
The sample works with the latest *released* version of Blazor (it was not tested against any *preview release*). 

You can [check the logs in your sendgrid account](https://sendgrid.com/docs/ui/analytics-and-reporting/email-activity-feed/) to help diagnose what may be happening.

**Comment by kvenda** [comment]
Thank you!
Karen
