### ISSUE TITLE
Removal of Weather Forecast and Weather Forecast Service

### ISSUE THREAD

**Issue by saboyle** [ADefWebserver/SyncfusionHelpDesk#3]
Is it worth removing the Weather files, unneeded / unreferenced (also removing from Startup.cs)?

**Comment by ADefWebserver** [comment]
The only reason I did not remove them was that I did not want to add any steps that were not _essential_ (to keep the page count small).

However, that means they 'remain' and this GitHub repo has to match the book.

However, in _your_ app, you should remove them :)

**Comment by saboyle** [comment]
Cool, makes sense.  Enjoyed the book btw, very useful.

Many thanks.

**Comment by ADefWebserver** [comment]
Thanks!
