### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ltemimi** [ADefWebserver/SyncfusionHelpDesk#7]
Hi 
I have requirements for a very similar app can I use the code from this repo? or is there copyright issues?

I intend to integrate and adapt the help desk with my current app, it will save me a lot of time

Thanks
Laz

**Comment by ADefWebserver** [comment]
I added a license that you can see here:
https://github.com/ADefWebserver/SyncfusionHelpDesk/blob/main/LICENSE

Basically you can use this code, no problem.
