### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by ltemimi** [ADefWebserver/SyncfusionHelpDesk#8]
Hi

Will the app work if I referenced bootstrap 4.x?

Thanks

Laz Temimi

**Comment by ADefWebserver** [comment]
It may. I have never tried that. Let us know what you find.

**Comment by ltemimi** [comment]
Hi
bootstrap works well :  
```<link href="_content/Syncfusion.Blazor/styles/bootstrap4.css" rel="stylesheet" />```
Thanks

**Comment by ADefWebserver** [comment]
@ltemimi - Thank you for this helpful information.
