### ISSUE TITLE
Original ticket can be edited when a user is logged in

### ISSUE THREAD

**Issue by ltemimi** [ADefWebserver/SyncfusionHelpDesk#9]
Hi
The original ticket i.e the top part can still be edited if a user is logged in as the role is not checked to keep isReadOnly = true it just relies on a user to be authenticated.

I know users do not have to register and login but who knows?

regards
Laz

**Comment by ADefWebserver** [comment]
That is by design to keep the accompanying book as short as possible. Thank you
